name: Build and Push Image
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: go-oidc-agent
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Containerfile

    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.QUAY_ROBOT_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_PASSWORD }}
        registry: quay.io

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/go-oidc-agent
